name: TinyChatManager
main: gloryrock.tinychatmanager.TinyChatManager
version: 1.1.0
api-version: 1.15
author: Gloryrock
description: A bloat-free chat management and formatting plugin
permissions:
      tinychatmanager.*:
        description: Wildcard permission
        default: op
        children:
          tinychatmanager.admin: true
      tinychatmanager.admin:
        description: Permission for all administrative actions.
        default: op
        children:
          tinychatmanager.use: true
          tinychatmanager.commands.reload: true
          tinychatmanager.commands.debug: true
          tinychatmanager.commands.set: true
          tinychatmanager.commands.user: true
          tinychatmanager.commands.user.update: true
          tinychatmanager.commands.user.info: true
          tinychatmanager.commands.user.setgroup: true
          tinychatmanager.commands.user.setsubgroup: true
          tinychatmanager.commands.database: true
          tinychatmanager.commands.database.migrate: true
          tinychatmanager.color.*: true
      tinychatmanager.use:
         description: Permission to use help commands.
         default: true
      tinychatmanager.user.custom.prefix:
         description: Permission to use custom prefixes per user.
         default: true
      tinychatmanager.user.custom.suffix:
         description: Permission to use custom suffixes per user.
         default: true
      tinychatmanager.commands.reload:
        description: Permission to reload configs and saved files.
        default: false
      tinychatmanager.commands.debug:
        description: Permission to display debug information.
        default: false
      tinychatmanager.commands.set:
        description: Permission to set user specific prefixes, suffixes, groups and colors.
        default: false
      tinychatmanager.commands.user:
        description: Permission to modify user configs.
        default: false
      tinychatmanager.commands.user.update:
        description: Permission to update user configs.
        default: false
      tinychatmanager.commands.user.info:
        description: Permission to display user information.
        default: false
      tinychatmanager.commands.user.setgroup:
        description: Permission to modify a user's group.
        default: false
      tinychatmanager.commands.user.setsubgroup:
        description: Permission to modify a user's subgroup.
        default: false
      tinychatmanager.commands.user.database:
        description: Permission to modify the database.
        default: false
      tinychatmanager.commands.user.database.migrate:
        description: Permission to migrate the database.
        default: false
      tinychatmanager.color.*:
        description: Permission to use all colors.
        default: true
        children:
          tinychatmanager.color.white: true
          tinychatmanager.color.black: true
          tinychatmanager.color.lightgray: true
          tinychatmanager.color.gray: true
          tinychatmanager.color.blue: true
          tinychatmanager.color.green: true
          tinychatmanager.color.cyan: true
          tinychatmanager.color.darkred: true
          tinychatmanager.color.purple: true
          tinychatmanager.color.gold: true
          tinychatmanager.color.lightblue: true
          tinychatmanager.color.lime: true
          tinychatmanager.color.aqua: true
          tinychatmanager.color.red: true
          tinychatmanager.color.magenta: true
          tinychatmanager.color.yellow: true
      tinychatmanager.color.white:
        description: Permission to use white.
        default: false
      tinychatmanager.color.black:
        description: Permission to use black.
        default: false
      tinychatmanager.color.lightgray:
        description: Permission to use lightgray.
        default: false
      tinychatmanager.color.gray:
        description: Permission gray.
        default: false
      tinychatmanager.color.blue:
        description: Permission to use blue.
        default: false
      tinychatmanager.color.green:
        description: Permission to use green.
        default: false
      tinychatmanager.color.cyan:
        description: Permission to use cyan.
        default: false
      tinychatmanager.color.darkred:
        description: Permission to use darkred.
        default: false
      tinychatmanager.color.purple:
        description: Permission to use purple.
        default: false
      tinychatmanager.color.gold:
        description: Permission to use gold.
        default: false
      tinychatmanager.color.lightblue:
        description: Permission to use lightblue.
        default: false
      tinychatmanager.color.lime:
        description: Permission to use lime.
        default: false
      tinychatmanager.color.aqua:
        description: Permission to use aqua.
        default: false
      tinychatmanager.color.red:
        description: Permission to use red.
        default: false
      tinychatmanager.color.magenta:
        description: Permission to use magenta.
        default: false
      tinychatmanager.color.yellow:
        description: Permission to use yellow.
        default: false
commands:
   tinychatmanager:
      description: Display information about tinychatmanager commands.
      aliases: tcm
      permission: tinychatmanager.use
      permission-message: You do not have permission to use this command.
      usage: /tinychatmanager
   reload:
      description: Reload configs.
      permission: tinychatmanager.commands.reload
      permission-message: You do not have permission to use this command.
      usage: /tinychatmanager reload
   debug:
      description: Debug configs.
      permission: tinychatmanager.commands.debug
      permission-message: You do not have permission to use this command.
      usage: /tinychatmanager debug
   set:
      description: Set user specific prefixes, suffixes and colors.
      permission: tinychatmanager.commands.set
      permission-message: You do not have permission to use this command.
      usage: /tinychatmanager set
   user:
      description: Display information about user commands.
      permission: tinychatmanager.commands.user
      permission-message: You do not have permission to use this command.
      usage: /tinychatmanager user <Player>
   database:
      description: Display information about database commands.
      permission: tinychatmanager.commands.database
      permission-message: You do not have permission to use this command.
      usage: /tinychatmanager database